apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anurag-sh
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/anurag.sh.git
    path: kubernetes
    kustomize:
      images:
        - anurag-sh=ghcr.io/accurate0/anurag-sh:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: anurag-sh
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
